#! /bin/sh

killall -9 picom sxhkd dunst xfce4-power-manager

pgrep -x sxhkd > /dev/null || sxhkd &

dunst -config $HOME/.config/bspwm/dunstrc &

xset r rate 300 70 # set key repetition speed
xinput set-prop 11 187 0 # disable touchpad
xinput set-prop 9 187 0 # disable touchscreen

setxkbmap -option compose:prsc
#$HOME/.config/polybar/launch.sh --hack
$HOME/.config/polybar_custom/launch.sh

xfce4-power-manager &

while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/bspwm/picom.conf &

bspc monitor -d 1 2 3 4 5 6 7 8
bspc monitor HDMI-2 -d H1 H2 H3 H4 H5 H6 H7 H8

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill ~/Pictures/circuiti_lenny.jpg
